/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculator;

/**
 *
 * @author uminduchethiya
 */
public class calulator extends javax.swing.JFrame {

    double num1, num2, res;
    String opretion;
    //private Object math;

    Stack stack = new Stack(100);
    Stack stack2 = new Stack(100);
    Stack stack3 = new Stack(100);

    public calulator() {
        super("calculator");
        initComponents();
        Disable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtdisplay = new javax.swing.JTextField();
        btnon = new javax.swing.JButton();
        btnhistory = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        btnseven = new javax.swing.JButton();
        btnfour = new javax.swing.JButton();
        btnone = new javax.swing.JButton();
        btndot = new javax.swing.JButton();
        btneight = new javax.swing.JButton();
        btnfive = new javax.swing.JButton();
        btntwo = new javax.swing.JButton();
        btnzero = new javax.swing.JButton();
        btnnine = new javax.swing.JButton();
        btnsix = new javax.swing.JButton();
        btnthree = new javax.swing.JButton();
        btnequal = new javax.swing.JButton();
        btndivition = new javax.swing.JButton();
        btnmultiply = new javax.swing.JButton();
        btnplus = new javax.swing.JButton();
        btnmin = new javax.swing.JButton();
        btnsqroot = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnlog = new javax.swing.JButton();
        btnsin = new javax.swing.JButton();
        btnx = new javax.swing.JButton();
        btnsecondpower = new javax.swing.JButton();
        btn3power = new javax.swing.JButton();
        btncos = new javax.swing.JButton();
        btncor = new javax.swing.JButton();
        btntan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtdisplay2 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        txtdisplay.setName("txtview"); // NOI18N
        txtdisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdisplayActionPerformed(evt);
            }
        });
        getContentPane().add(txtdisplay);
        txtdisplay.setBounds(10, 50, 234, 40);

        btnon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnon.setText("ON");
        btnon.setName(""); // NOI18N
        btnon.setPreferredSize(new java.awt.Dimension(45, 44));
        btnon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnonActionPerformed(evt);
            }
        });
        getContentPane().add(btnon);
        btnon.setBounds(10, 100, 54, 40);

        btnhistory.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnhistory.setText("H");
        btnhistory.setName("btnon"); // NOI18N
        btnhistory.setPreferredSize(new java.awt.Dimension(45, 44));
        btnhistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhistoryActionPerformed(evt);
            }
        });
        getContentPane().add(btnhistory);
        btnhistory.setBounds(70, 100, 54, 40);

        btnclear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnclear.setText("C");
        btnclear.setName("btnon"); // NOI18N
        btnclear.setPreferredSize(new java.awt.Dimension(45, 44));
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear);
        btnclear.setBounds(130, 100, 54, 40);

        btnback.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnback.setText(">");
        btnback.setName("btnon"); // NOI18N
        btnback.setPreferredSize(new java.awt.Dimension(45, 44));
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        getContentPane().add(btnback);
        btnback.setBounds(190, 100, 54, 40);

        btnseven.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnseven.setText("7");
        btnseven.setName(""); // NOI18N
        btnseven.setPreferredSize(new java.awt.Dimension(45, 44));
        btnseven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsevenActionPerformed(evt);
            }
        });
        getContentPane().add(btnseven);
        btnseven.setBounds(10, 150, 54, 40);

        btnfour.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnfour.setText("4");
        btnfour.setName(""); // NOI18N
        btnfour.setPreferredSize(new java.awt.Dimension(45, 44));
        btnfour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfourActionPerformed(evt);
            }
        });
        getContentPane().add(btnfour);
        btnfour.setBounds(10, 200, 54, 40);

        btnone.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnone.setText("1");
        btnone.setName(""); // NOI18N
        btnone.setPreferredSize(new java.awt.Dimension(45, 44));
        btnone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoneActionPerformed(evt);
            }
        });
        getContentPane().add(btnone);
        btnone.setBounds(10, 250, 54, 40);

        btndot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btndot.setText(".");
        btndot.setName(""); // NOI18N
        btndot.setPreferredSize(new java.awt.Dimension(45, 44));
        btndot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndotActionPerformed(evt);
            }
        });
        getContentPane().add(btndot);
        btndot.setBounds(10, 300, 54, 40);

        btneight.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btneight.setText("8");
        btneight.setName("btnon"); // NOI18N
        btneight.setPreferredSize(new java.awt.Dimension(45, 44));
        btneight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneightActionPerformed(evt);
            }
        });
        getContentPane().add(btneight);
        btneight.setBounds(70, 150, 54, 40);

        btnfive.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnfive.setText("5");
        btnfive.setName("btnon"); // NOI18N
        btnfive.setPreferredSize(new java.awt.Dimension(45, 44));
        btnfive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfiveActionPerformed(evt);
            }
        });
        getContentPane().add(btnfive);
        btnfive.setBounds(70, 200, 54, 40);

        btntwo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btntwo.setText("2");
        btntwo.setName("btnon"); // NOI18N
        btntwo.setPreferredSize(new java.awt.Dimension(45, 44));
        btntwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntwoActionPerformed(evt);
            }
        });
        getContentPane().add(btntwo);
        btntwo.setBounds(70, 250, 54, 40);

        btnzero.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnzero.setText("0");
        btnzero.setName("btnon"); // NOI18N
        btnzero.setPreferredSize(new java.awt.Dimension(45, 44));
        btnzero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnzeroActionPerformed(evt);
            }
        });
        getContentPane().add(btnzero);
        btnzero.setBounds(70, 300, 54, 40);

        btnnine.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnnine.setText("9");
        btnnine.setName("btnon"); // NOI18N
        btnnine.setPreferredSize(new java.awt.Dimension(45, 44));
        btnnine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnineActionPerformed(evt);
            }
        });
        getContentPane().add(btnnine);
        btnnine.setBounds(130, 150, 54, 40);

        btnsix.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnsix.setText("6");
        btnsix.setName("btnon"); // NOI18N
        btnsix.setPreferredSize(new java.awt.Dimension(45, 44));
        btnsix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsixActionPerformed(evt);
            }
        });
        getContentPane().add(btnsix);
        btnsix.setBounds(130, 200, 54, 40);

        btnthree.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnthree.setText("3");
        btnthree.setName("btnon"); // NOI18N
        btnthree.setPreferredSize(new java.awt.Dimension(45, 44));
        btnthree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthreeActionPerformed(evt);
            }
        });
        getContentPane().add(btnthree);
        btnthree.setBounds(130, 250, 54, 40);

        btnequal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnequal.setText("=");
        btnequal.setName("btnon"); // NOI18N
        btnequal.setPreferredSize(new java.awt.Dimension(45, 44));
        btnequal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnequalActionPerformed(evt);
            }
        });
        getContentPane().add(btnequal);
        btnequal.setBounds(130, 300, 54, 40);

        btndivition.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btndivition.setText("/");
        btndivition.setName("btnon"); // NOI18N
        btndivition.setPreferredSize(new java.awt.Dimension(45, 44));
        btndivition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndivitionActionPerformed(evt);
            }
        });
        getContentPane().add(btndivition);
        btndivition.setBounds(190, 150, 54, 40);

        btnmultiply.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnmultiply.setText("*");
        btnmultiply.setName("btnon"); // NOI18N
        btnmultiply.setPreferredSize(new java.awt.Dimension(45, 44));
        btnmultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmultiplyActionPerformed(evt);
            }
        });
        getContentPane().add(btnmultiply);
        btnmultiply.setBounds(190, 200, 54, 40);

        btnplus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnplus.setText("+");
        btnplus.setName("btnon"); // NOI18N
        btnplus.setPreferredSize(new java.awt.Dimension(45, 44));
        btnplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplusActionPerformed(evt);
            }
        });
        getContentPane().add(btnplus);
        btnplus.setBounds(190, 300, 54, 40);

        btnmin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnmin.setText("-");
        btnmin.setName("btnon"); // NOI18N
        btnmin.setPreferredSize(new java.awt.Dimension(45, 44));
        btnmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnminActionPerformed(evt);
            }
        });
        getContentPane().add(btnmin);
        btnmin.setBounds(190, 250, 54, 40);

        btnsqroot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnsqroot.setText("√");
        btnsqroot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsqrootActionPerformed(evt);
            }
        });
        getContentPane().add(btnsqroot);
        btnsqroot.setBounds(270, 100, 100, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("(-)");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(380, 100, 100, 40);

        btnlog.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnlog.setText("Log");
        btnlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogActionPerformed(evt);
            }
        });
        getContentPane().add(btnlog);
        btnlog.setBounds(380, 150, 100, 40);

        btnsin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnsin.setText("Sin");
        btnsin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsinActionPerformed(evt);
            }
        });
        getContentPane().add(btnsin);
        btnsin.setBounds(380, 200, 100, 40);

        btnx.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnx.setText("X");
        btnx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxActionPerformed(evt);
            }
        });
        getContentPane().add(btnx);
        btnx.setBounds(270, 150, 109, 40);

        btnsecondpower.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnsecondpower.setText("X^2");
        btnsecondpower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsecondpowerActionPerformed(evt);
            }
        });
        getContentPane().add(btnsecondpower);
        btnsecondpower.setBounds(270, 200, 109, 40);

        btn3power.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn3power.setText("X^3");
        btn3power.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3powerActionPerformed(evt);
            }
        });
        getContentPane().add(btn3power);
        btn3power.setBounds(270, 250, 109, 40);

        btncos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btncos.setText("Cos");
        btncos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncosActionPerformed(evt);
            }
        });
        getContentPane().add(btncos);
        btncos.setBounds(380, 250, 100, 40);

        btncor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btncor.setText("X^Y");
        btncor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncorActionPerformed(evt);
            }
        });
        getContentPane().add(btncor);
        btncor.setBounds(270, 300, 109, 40);

        btntan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btntan.setText("Tan");
        btntan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntanActionPerformed(evt);
            }
        });
        getContentPane().add(btntan);
        btntan.setBounds(380, 300, 100, 40);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(330, 20, 0, 0);

        txtdisplay2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdisplay2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtdisplay2);
        txtdisplay2.setBounds(10, 0, 210, 40);

        jMenu1.setText("File");

        jMenuItem1.setText("Standard");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Scientific");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Exit");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem4.setText("History");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public void operation() {

        String ans;
        
        num2 = Double.parseDouble(txtdisplay.getText());
        if (opretion == "+") {

            res = num1 + num2;
            ans = String.format("%.2f", res);
            txtdisplay.setText(ans);

        } else if (opretion == "-") {

            res = num1 - num2;
            ans = String.format("%.2f", res);
            txtdisplay.setText(ans);

        } else if (opretion == "*") {

            res = num1 * num2;
            ans = String.format("%.2f", res);
            txtdisplay.setText(ans);

        } else if (opretion == "/") {

            res = num1 / num2;
            ans = String.format("%.2f", res);
            txtdisplay.setText(ans);

        }

    }

    public void Disable() {

        btnhistory.setEnabled(false);
        btnclear.setEnabled(false);
        btnback.setEnabled(false);
        btndivition.setEnabled(false);
        btnmultiply.setEnabled(false);
        btnmin.setEnabled(false);
        btnplus.setEnabled(false);
        btnequal.setEnabled(false);
        btndot.setEnabled(false);
        btnzero.setEnabled(false);
        btnone.setEnabled(false);
        btntwo.setEnabled(false);
        btnthree.setEnabled(false);
        btnfour.setEnabled(false);
        btnfive.setEnabled(false);
        btnsix.setEnabled(false);
        btnseven.setEnabled(false);
        btneight.setEnabled(false);
        btnnine.setEnabled(false);
        btnsqroot.setEnabled(false);
        btnx.setEnabled(false);
        btnsecondpower.setEnabled(false);
        btn3power.setEnabled(false);
        btncor.setEnabled(false);
        jButton2.setEnabled(false);
        btnlog.setEnabled(false);
        btnsin.setEnabled(false);
        btncos.setEnabled(false);
        btntan.setEnabled(false);

    }

    public void Enable() {

        btnhistory.setEnabled(true);
        btnclear.setEnabled(true);
        btnback.setEnabled(true);
        btndivition.setEnabled(true);
        btnmultiply.setEnabled(true);
        btnmin.setEnabled(true);
        btnplus.setEnabled(true);
        btnequal.setEnabled(true);
        btndot.setEnabled(true);
        btnzero.setEnabled(true);
        btnone.setEnabled(true);
        btntwo.setEnabled(true);
        btnthree.setEnabled(true);
        btnfour.setEnabled(true);
        btnfive.setEnabled(true);
        btnsix.setEnabled(true);
        btnseven.setEnabled(true);
        btneight.setEnabled(true);
        btnnine.setEnabled(true);
        btnsqroot.setEnabled(true);
        btnx.setEnabled(true);
        btnsecondpower.setEnabled(true);
        btn3power.setEnabled(true);
        btncor.setEnabled(true);
        jButton2.setEnabled(true);
        btnlog.setEnabled(true);
        btnsin.setEnabled(true);
        btncos.setEnabled(true);
        btntan.setEnabled(true);

    }

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.setResizable(true);
        this.setSize(230, 400);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnonActionPerformed
        if (btnon.isSelected()) {
            Disable();

        } else {
            Enable();

        }
    }//GEN-LAST:event_btnonActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        txtdisplay.setText("");
        txtdisplay2.setText("");
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        int length = txtdisplay.getText().length();
        int number = txtdisplay.getText().length() - 1;
        String store;

        if (length > 0) {
            StringBuilder back = new StringBuilder(txtdisplay.getText());
            back.deleteCharAt(number);
            store = back.toString();
            txtdisplay.setText(store);

        }
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnsevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsevenActionPerformed
        String iNum = txtdisplay.getText() + btnseven.getText();
        txtdisplay.setText(iNum);
    }//GEN-LAST:event_btnsevenActionPerformed

    private void btnfourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfourActionPerformed
        String iNum = txtdisplay.getText() + btnfour.getText();
        txtdisplay.setText(iNum);
    }//GEN-LAST:event_btnfourActionPerformed

    private void btnoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoneActionPerformed
        String iNum = txtdisplay.getText() + btnone.getText();
        txtdisplay.setText(iNum);
    }//GEN-LAST:event_btnoneActionPerformed

    private void btndotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndotActionPerformed
        if (!txtdisplay.getText().contains(".")) {

            txtdisplay.setText(txtdisplay.getText() + btndot.getText());

        }
    }//GEN-LAST:event_btndotActionPerformed

    private void btnnineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnineActionPerformed
        String iNum = txtdisplay.getText() + btnnine.getText();
        txtdisplay.setText(iNum);
    }//GEN-LAST:event_btnnineActionPerformed

    private void btnsixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsixActionPerformed
        String iNum = txtdisplay.getText() + btnsix.getText();
        txtdisplay.setText(iNum);
    }//GEN-LAST:event_btnsixActionPerformed

    private void btnthreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthreeActionPerformed
        String iNum = txtdisplay.getText() + btnthree.getText();
        txtdisplay.setText(iNum);
    }//GEN-LAST:event_btnthreeActionPerformed

    private void btnequalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnequalActionPerformed

        txtdisplay2.setText(txtdisplay2.getText() + txtdisplay.getText());
        operation();
        stack.push(txtdisplay.getText());
        stack2.push(txtdisplay2.getText());
        stack3.push(txtdisplay2.getText() + " = " + txtdisplay.getText());

    }//GEN-LAST:event_btnequalActionPerformed

    private void btndivitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndivitionActionPerformed

        num1 = Double.parseDouble(txtdisplay.getText());
        txtdisplay2.setText(txtdisplay.getText() + " / ");
        txtdisplay.setText("");
        opretion = ("/");
    }//GEN-LAST:event_btndivitionActionPerformed

    private void btnmultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmultiplyActionPerformed
        num1 = Double.parseDouble(txtdisplay.getText());
        txtdisplay2.setText(txtdisplay.getText() + " * ");
        txtdisplay.setText("");
        opretion = ("*");
    }//GEN-LAST:event_btnmultiplyActionPerformed

    private void btnplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplusActionPerformed
        num1 = Double.parseDouble(txtdisplay.getText());
        txtdisplay2.setText(txtdisplay.getText() + " + ");
        txtdisplay.setText("");
        opretion = ("+");
    }//GEN-LAST:event_btnplusActionPerformed

    private void btnminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnminActionPerformed
        num1 = Double.parseDouble(txtdisplay.getText());
        txtdisplay2.setText(txtdisplay.getText() + " - ");
        txtdisplay.setText("");
        opretion = ("-");

    }//GEN-LAST:event_btnminActionPerformed

    private void btnzeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnzeroActionPerformed
        String iNum = txtdisplay.getText() + btnzero.getText();
        txtdisplay.setText(iNum);
    }//GEN-LAST:event_btnzeroActionPerformed

    private void btnxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxActionPerformed
        double ops;
        ops = (3.1428571428571428571428571428571);
        txtdisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_btnxActionPerformed

    private void btnsecondpowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsecondpowerActionPerformed
        double ops = Double.parseDouble(String.valueOf(txtdisplay.getText()));
        ops = (ops * ops);
        txtdisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_btnsecondpowerActionPerformed

    private void btntanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntanActionPerformed
        double ops = Double.parseDouble(String.valueOf(txtdisplay.getText()));
        ops = Math.tan(ops);
        txtdisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_btntanActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        double ops = Double.parseDouble(String.valueOf(txtdisplay.getText()));
        ops = ops * (-1);
        txtdisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btneightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneightActionPerformed
        String iNum = txtdisplay.getText() + btneight.getText();
        txtdisplay.setText(iNum);
    }//GEN-LAST:event_btneightActionPerformed

    private void btnfiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfiveActionPerformed
        String iNum = txtdisplay.getText() + btnfive.getText();
        txtdisplay.setText(iNum);
    }//GEN-LAST:event_btnfiveActionPerformed

    private void btntwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntwoActionPerformed
        String iNum = txtdisplay.getText() + btntwo.getText();
        txtdisplay.setText(iNum);
    }//GEN-LAST:event_btntwoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.setResizable(true);
        txtdisplay.setSize(360, 40);
        this.setSize(500, 400);

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.setResizable(true);
        this.setSize(250, 400);
    }//GEN-LAST:event_formWindowActivated

    private void txtdisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdisplayActionPerformed

    private void btn3powerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3powerActionPerformed
        double ops = Double.parseDouble(String.valueOf(txtdisplay.getText()));
        ops = (ops * ops * ops);
        txtdisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_btn3powerActionPerformed

    private void btncorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncorActionPerformed
        double ops = Double.parseDouble(String.valueOf(txtdisplay.getText()));
        ops = Math.pow(ops, ops);
        txtdisplay.setText(String.valueOf(ops));

    }//GEN-LAST:event_btncorActionPerformed

    private void btncosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncosActionPerformed
        double ops = Double.parseDouble(String.valueOf(txtdisplay.getText()));
        ops = Math.cos(ops);
        txtdisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_btncosActionPerformed

    private void btnsinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsinActionPerformed
        double ops = Double.parseDouble(String.valueOf(txtdisplay.getText()));
        ops = Math.sin(ops);
        txtdisplay.setText(String.valueOf(ops));

    }//GEN-LAST:event_btnsinActionPerformed

    private void btnlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogActionPerformed
        double ops = Double.parseDouble(String.valueOf(txtdisplay.getText()));
        ops = Math.log(ops);
        txtdisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_btnlogActionPerformed

    private void btnsqrootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsqrootActionPerformed

        double ops = Double.parseDouble(String.valueOf(txtdisplay.getText()));
        ops = Math.sqrt(ops);
        txtdisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_btnsqrootActionPerformed

    private void btnhistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhistoryActionPerformed
        if (stack.isEmpty() == true) {
            txtdisplay.setText("-999");
            txtdisplay2.setText("-999");
        } else {

            txtdisplay.setText(stack.printStack());
            txtdisplay2.setText(stack2.printStack());
            stack.pop();
            stack2.pop();

        }
    }//GEN-LAST:event_btnhistoryActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        setVisible(false);
        History ob = new History();
        ob.setVisible(true);
        ob.setData(stack3.getData());
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void txtdisplay2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdisplay2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdisplay2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn3power;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btncor;
    private javax.swing.JButton btncos;
    private javax.swing.JButton btndivition;
    private javax.swing.JButton btndot;
    private javax.swing.JButton btneight;
    private javax.swing.JButton btnequal;
    private javax.swing.JButton btnfive;
    private javax.swing.JButton btnfour;
    private javax.swing.JButton btnhistory;
    private javax.swing.JButton btnlog;
    private javax.swing.JButton btnmin;
    private javax.swing.JButton btnmultiply;
    private javax.swing.JButton btnnine;
    private javax.swing.JButton btnon;
    private javax.swing.JButton btnone;
    private javax.swing.JButton btnplus;
    private javax.swing.JButton btnsecondpower;
    private javax.swing.JButton btnseven;
    private javax.swing.JButton btnsin;
    private javax.swing.JButton btnsix;
    private javax.swing.JButton btnsqroot;
    private javax.swing.JButton btntan;
    private javax.swing.JButton btnthree;
    private javax.swing.JButton btntwo;
    private javax.swing.JButton btnx;
    private javax.swing.JButton btnzero;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JTextField txtdisplay;
    private javax.swing.JTextField txtdisplay2;
    // End of variables declaration//GEN-END:variables
}
